### ISSUE TITLE
Telegram Bot

### ISSUE THREAD

**Issue by tecnologiamvv** [jptsantossilva/BEC#15]
Hello, I want to congratulate you for the good work.

I am having this frequent error: send_telegram_message - An Http Error occurred:HTTPError('404 Client Error: Not Found for url: https://api.telegram.org/botNone/sendMessage?text=

It's like the bot doesn't get the token entered in the configuration.

**Comment by jptsantossilva** [comment]
Hi,

On the error message the address has the string "botNone", so most probably
the solution is one of the below.


Since the telegram bot names are stored as environment variables make sure
you logout and login or restart computer to set the environment variables.

Also, make sure the bot names in the environment variables are typed
correctly.

--
Melhores Cumprimentos / Best Regards

João Santos Silva

A segunda, 26/06/2023, 23:02, Tecnologia Verbo da Vida <
***@***.***> escreveu:

**Comment by tecnologiamvv** [comment]
Ok. Thanks. I will check.

**Comment by tecnologiamvv** [comment]
send_telegram_message - An Http Error occurred:HTTPError('404 Client Error: Not Found for url: https://api.telegram.org/botNone/sendMessage?chat_id=1396

Error remains even restarting the vps. The data is correctly entered.
